[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
create_nft = "DtwR5igWmGM14GSgS844Szeh9qvSZt4HPie96bw7Dbqv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/chris/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
